version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 5
    target-branch: "develop"
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
