version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
